apiVersion: v1
kind: Namespace
metadata:
  name: hw-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hw-app
  name: hw-deploy
  labels:
    app: hw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: hw
        image: inventadenos/helloworld:latest
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  namespace: hw-app
  name: hw-svc
  labels:
    app: hw
spec:
  selector:
    app: hw
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hw-app
  name: hw-ing
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: "traefik"
  rules:
  - host: "ufuoma.thecloudacademy.org"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hw-svc
            port:
              name: web
  tls:
  - hosts:
    - ufuoma.thecloudacademy.org
    secretName: mmy-cert-tls-zgrhz  